export const ActionType = {
	UPDATE_AVATAR: 'UPDATE_AVATAR',
	TRUST_PARTNER: 'TRUST_PARTNER',
	SHIELDED_PARTNER: 'SHIELDED_PARTNER',
	CHANGE_USER_NAME: 'CHANGE_USER_NAME',
	USER_LOGOUT: 'USER_LOGOUT',
	USER_LOGIN: 'USER_LOGIN',
	UPDATE_GA_STATSUS: 'UPDATE_GA_STATSUS',
	UPDATE_FUND_PASSWORD: 'UPDATE_FUND_PASSWORD'
};